#!/usr/bin/env php
<?php

use Eusouomichel\PhpCommit\Application;

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $autoloadFile) {
    if (file_exists($autoloadFile)) {
        require $autoloadFile;
        break;
    }
}

$app = new Application();
$app->run();
